from enum import Enum


class KeyWord(Enum):
    query = "query"
    limit = "limit"
    page = "page"
    page_info = "pageInfo"
    number_of_hits = "numberOfHits"
    results = "results"
    current_page = "current"
    total_page = "total"
    ids = "ids"
    base64 = "base64"
    show_key = "showKey"
    showIds = "showIds"
    termBoxWidth = "termBoxWidth"
    termBoxHeight = "termBoxHeight"
    showSlimColours = "showSlimColours"
    showChildren = "showChildren"
    fontSize = "fontSize"
    slims_to_Ids = "slimsToIds"
    slims_from_Ids = "slimsFromIds"
    relations = "relations"
    start_ids = "startIds"
    stop_ids = "stopIds"
    edges = "edges"
    vertices = "vertices"
